[project]
name = "stockprediction"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "asyncpg>=0.30.0",
    "fastapi>=0.115.11",
    "pydantic>=2.10.6",
    "sqlalchemy>=2.0.38",
    "torch>=2.6.0+cu126",
]
