apiVersion: apps/v1
kind: Deployment
metadata:
  name: data-ingestion
spec:
  template:
    spec:
      containers:
      - name: data-ingestion
        resources:
          # Minimum resources guaranteed to the container
          # 1Gi RAM is sufficient for data processing operations
          # 500m CPU = 0.5 CPU cores
          requests:
            memory: "1Gi"
            cpu: "500m"
          # Maximum resources the container can use
          # 2Gi RAM allows for handling larger datasets without OOM errors
          # 1000m CPU = 1 CPU core
          limits:
            memory: "2Gi"
            cpu: "1000m"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: model-service
spec:
  template:
    spec:
      containers:
      - name: model-service
        resources:
          # Minimum resources guaranteed to the container
          # 4Gi RAM is needed for loading models into memory
          # 2000m CPU = 2 CPU cores for model training/inference
          requests:
            memory: "4Gi"
            cpu: "2000m"
          # Maximum resources the container can use
          # 8Gi RAM allows for training larger models
          # 4000m CPU = 4 CPU cores for parallel processing
          limits:
            memory: "8Gi"
            cpu: "4000m"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: dashboard-service
spec:
  template:
    spec:
      containers:
      - name: dashboard-service
        resources:
          # Minimum resources guaranteed to the container
          # 1Gi RAM is sufficient for serving web content
          # 500m CPU = 0.5 CPU cores
          requests:
            memory: "1Gi"
            cpu: "500m"
          # Maximum resources the container can use
          # 2Gi RAM allows for handling many concurrent connections
          # 1000m CPU = 1 CPU core
          limits:
            memory: "2Gi"
            cpu: "1000m"